version: "3.3"

services:
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "54321:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  celery:
    build: .
    command: celery -A core worker -P gevent -l INFO --concurrency=50
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"