# Generated by Django 2.2.17 on 2022-05-16 16:36

from django.db import migrations

def forward(apps, schema_editor):
    ProposalRequirements = apps.get_model("credit_proposal", "ProposalRequirements")
    ProposalRequirements.objects.create(
        proposal_required_fields={
            "cpf": "number",
            "cnpj": "number",
            "reason": "text"
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('credit_proposal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
