name: Django Tests
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Copy env
        working-directory: ./backend
        run: |
          cp -f .env.sample .env
      - name: Test with pytest
        working-directory: ./backend
        run: |
          export DJANGO_SETTINGS_MODULE=core.settings_test
          py.test
        env:
          SECRET_KEY: teste
          DEBUG: True
          ALLOWED_HOSTS: 0.0.0.0,127.0.0.1,localhost
          DB_ENGINE: teste
          POSTGRES_DB: teste
          POSTGRES_USER: teste
          POSTGRES_PASSWORD: teste
          DB_HOST: teste
          DB_PORT: teste
