name: Django Tests
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Copy env
        working-directory: ./backend
        run: |
          cp -f .env.sample .env
          export DJANGO_SETTINGS_MODULE=core.settings_test
          export $(grep -v '^#' .env | xargs)
      - name: Backend code lint
        working-directory: ./backend
        run: |
          flake8
      - name: Test with pytest
        working-directory: ./backend
        run: |
          py.test
